[project]
name = "buff-p"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "av>=17.0.1",
    "dotenv>=0.9.9",
    "edge-tts>=7.2.8",
    "fastapi>=0.136.3",
    "flet>=0.85.1",
    "google-auth>=2.53.0",
    "joblib>=1.5.3",
    "line-bot-sdk>=3.23.1",
    "onvif-zeep>=0.2.12",
    "opencv-python>=4.13.0.92",
    "pillow>=12.2.0",
    "pygame>=2.6.1",
    "pyjwt>=2.13.0",
    "python-multipart>=0.0.30",
    "qrcode>=8.2",
    "scikit-learn>=1.8.0",
    "PyTurboJPEG>=1.7.1",
    "ultralytics>=8.4.53",
    "uvicorn>=0.48.0",
    "wsdiscovery>=2.1.2",
    "deepface>=0.0.100",
    "tf-keras>=2.21.0",
]

[tool.pyright]
executionEnvironments = [
  { root = "." }
]
extraPaths = ["."]
